/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 22/07/2015 06:09:12
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            25000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_SYSCLKFreq_VALUE                     16000000
#define MX_HCLKFreq_Value                       16000000
#define MX_FCLKCortexFreq_Value                 16000000
#define MX_CortexFreq_Value                     16000000
#define MX_AHBFreq_Value                        16000000
#define MX_APB1Freq_Value                       16000000
#define MX_APB2Freq_Value                       16000000
#define MX_APB1TimFreq_Value                    16000000
#define MX_APB2TimFreq_Value                    16000000
#define MX_48MHZClocksFreq_Value                48000000
#define MX_EthernetFreq_Value                   16000000
#define MX_I2SClocksFreq_Value                  96000000
#define MX_WatchDogFreq_Value                   32000
#define MX_RTCFreq_Value                        32000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    16000000

/*-------------------------------- DMA        --------------------------------*/

#define MX_DMA                                  1

/* NVIC Configuration */

/* NVIC DMA2_Stream4_IRQn */
#define MX_DMA2_Stream4_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream4_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream4_IRQn_Subriority         0

/* NVIC DMA1_Stream3_IRQn */
#define MX_DMA1_Stream3_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream3_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream3_IRQn_Subriority         0

/* NVIC DMA2_Stream1_IRQn */
#define MX_DMA2_Stream1_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream1_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream1_IRQn_Subriority         0

/* NVIC DMA1_Stream0_IRQn */
#define MX_DMA1_Stream0_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream0_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream0_IRQn_Subriority         0

/*-------------------------------- I2C1       --------------------------------*/

#define MX_I2C1                                 1

/* GPIO Configuration */

/* Pin PB6 */
#define MX_I2C1_SCL_GPIO_Speed                  GPIO_SPEED_HIGH
#define MX_I2C1_SCL_Pin                         PB6
#define MX_I2C1_SCL_GPIOx                       GPIOB
#define MX_I2C1_SCL_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C1_SCL_GPIO_Pin                    GPIO_PIN_6
#define MX_I2C1_SCL_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PB7 */
#define MX_I2C1_SDA_GPIO_Speed                  GPIO_SPEED_HIGH
#define MX_I2C1_SDA_Pin                         PB7
#define MX_I2C1_SDA_GPIOx                       GPIOB
#define MX_I2C1_SDA_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C1_SDA_GPIO_Pin                    GPIO_PIN_7
#define MX_I2C1_SDA_GPIO_AF                     GPIO_AF4_I2C1
#define MX_I2C1_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/*-------------------------------- I2C2       --------------------------------*/

#define MX_I2C2                                 1

/* GPIO Configuration */

/* Pin PF0 */
#define MX_I2C2_SDA_GPIO_Speed                  GPIO_SPEED_HIGH
#define MX_I2C2_SDA_Pin                         PF0
#define MX_I2C2_SDA_GPIOx                       GPIOF
#define MX_I2C2_SDA_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C2_SDA_GPIO_Pin                    GPIO_PIN_0
#define MX_I2C2_SDA_GPIO_AF                     GPIO_AF4_I2C2
#define MX_I2C2_SDA_GPIO_Mode                   GPIO_MODE_AF_OD

/* Pin PF1 */
#define MX_I2C2_SCL_GPIO_Speed                  GPIO_SPEED_HIGH
#define MX_I2C2_SCL_Pin                         PF1
#define MX_I2C2_SCL_GPIOx                       GPIOF
#define MX_I2C2_SCL_GPIO_PuPdOD                 GPIO_PULLUP
#define MX_I2C2_SCL_GPIO_Pin                    GPIO_PIN_1
#define MX_I2C2_SCL_GPIO_AF                     GPIO_AF4_I2C2
#define MX_I2C2_SCL_GPIO_Mode                   GPIO_MODE_AF_OD

/*-------------------------------- I2S2       --------------------------------*/

#define MX_I2S2                                 1

/* GPIO Configuration */

/* Pin PB12 */
#define MX_I2S2_WS_GPIO_Speed                   GPIO_SPEED_LOW
#define MX_I2S2_WS_Pin                          PB12
#define MX_I2S2_WS_GPIOx                        GPIOB
#define MX_I2S2_WS_GPIO_PuPd                    GPIO_NOPULL
#define MX_I2S2_WS_GPIO_Pin                     GPIO_PIN_12
#define MX_I2S2_WS_GPIO_AF                      GPIO_AF5_SPI2
#define MX_I2S2_WS_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PC3 */
#define MX_I2S2_SD_GPIO_Speed                   GPIO_SPEED_LOW
#define MX_I2S2_SD_Pin                          PC3
#define MX_I2S2_SD_GPIOx                        GPIOC
#define MX_I2S2_SD_GPIO_PuPd                    GPIO_NOPULL
#define MX_I2S2_SD_GPIO_Pin                     GPIO_PIN_3
#define MX_I2S2_SD_GPIO_AF                      GPIO_AF5_SPI2
#define MX_I2S2_SD_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PB10 */
#define MX_I2S2_CK_GPIO_Speed                   GPIO_SPEED_LOW
#define MX_I2S2_CK_Pin                          PB10
#define MX_I2S2_CK_GPIOx                        GPIOB
#define MX_I2S2_CK_GPIO_PuPd                    GPIO_NOPULL
#define MX_I2S2_CK_GPIO_Pin                     GPIO_PIN_10
#define MX_I2S2_CK_GPIO_AF                      GPIO_AF5_SPI2
#define MX_I2S2_CK_GPIO_Mode                    GPIO_MODE_AF_PP

/* DMA Configuration */

/* DMA SPI2_RX */
#define MX_SPI2_RX_DMA_MemBurst                 DMA_MBURST_SINGLE
#define MX_SPI2_RX_DMA_Instance                 DMA1_Stream3
#define MX_SPI2_RX_DMA_FIFOMode                 DMA_FIFOMODE_ENABLE
#define MX_SPI2_RX_DMA_Priority                 DMA_PRIORITY_LOW
#define MX_SPI2_RX_DMA_Channel                  DMA_CHANNEL_0
#define MX_SPI2_RX_DMA_MemDataAlignment         DMA_MDATAALIGN_WORD
#define MX_SPI2_RX_DMA_Mode                     DMA_CIRCULAR
#define MX_SPI2_RX_DMA_Direction                DMA_PERIPH_TO_MEMORY
#define MX_SPI2_RX_DMA_PeriphBurst              DMA_PBURST_SINGLE
#define MX_SPI2_RX_DMA_MemInc                   DMA_MINC_ENABLE
#define MX_SPI2_RX_DMA_PeriphDataAlignment      DMA_PDATAALIGN_HALFWORD
#define MX_SPI2_RX_DMA_PeriphInc                DMA_PINC_DISABLE
#define MX_SPI2_RX_DMA_FIFOThreshold            DMA_FIFO_THRESHOLD_HALFFULL

/*-------------------------------- I2S3       --------------------------------*/

#define MX_I2S3                                 1

/* GPIO Configuration */

/* Pin PA4 */
#define MX_I2S3_WS_GPIO_Speed                   GPIO_SPEED_LOW
#define MX_I2S3_WS_Pin                          PA4
#define MX_I2S3_WS_GPIOx                        GPIOA
#define MX_I2S3_WS_GPIO_PuPd                    GPIO_NOPULL
#define MX_I2S3_WS_GPIO_Pin                     GPIO_PIN_4
#define MX_I2S3_WS_GPIO_AF                      GPIO_AF6_SPI3
#define MX_I2S3_WS_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PC12 */
#define MX_I2S3_SD_GPIO_Speed                   GPIO_SPEED_LOW
#define MX_I2S3_SD_Pin                          PC12
#define MX_I2S3_SD_GPIOx                        GPIOC
#define MX_I2S3_SD_GPIO_PuPd                    GPIO_NOPULL
#define MX_I2S3_SD_GPIO_Pin                     GPIO_PIN_12
#define MX_I2S3_SD_GPIO_AF                      GPIO_AF6_SPI3
#define MX_I2S3_SD_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PC10 */
#define MX_I2S3_CK_GPIO_Speed                   GPIO_SPEED_LOW
#define MX_I2S3_CK_Pin                          PC10
#define MX_I2S3_CK_GPIOx                        GPIOC
#define MX_I2S3_CK_GPIO_PuPd                    GPIO_NOPULL
#define MX_I2S3_CK_GPIO_Pin                     GPIO_PIN_10
#define MX_I2S3_CK_GPIO_AF                      GPIO_AF6_SPI3
#define MX_I2S3_CK_GPIO_Mode                    GPIO_MODE_AF_PP

/* DMA Configuration */

/* DMA SPI3_RX */
#define MX_SPI3_RX_DMA_MemBurst                 DMA_MBURST_SINGLE
#define MX_SPI3_RX_DMA_Instance                 DMA1_Stream0
#define MX_SPI3_RX_DMA_FIFOMode                 DMA_FIFOMODE_ENABLE
#define MX_SPI3_RX_DMA_Priority                 DMA_PRIORITY_LOW
#define MX_SPI3_RX_DMA_Channel                  DMA_CHANNEL_0
#define MX_SPI3_RX_DMA_MemDataAlignment         DMA_MDATAALIGN_WORD
#define MX_SPI3_RX_DMA_Mode                     DMA_CIRCULAR
#define MX_SPI3_RX_DMA_Direction                DMA_PERIPH_TO_MEMORY
#define MX_SPI3_RX_DMA_PeriphBurst              DMA_PBURST_SINGLE
#define MX_SPI3_RX_DMA_MemInc                   DMA_MINC_ENABLE
#define MX_SPI3_RX_DMA_PeriphDataAlignment      DMA_PDATAALIGN_HALFWORD
#define MX_SPI3_RX_DMA_PeriphInc                DMA_PINC_DISABLE
#define MX_SPI3_RX_DMA_FIFOThreshold            DMA_FIFO_THRESHOLD_HALFFULL

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- SAI1       --------------------------------*/

#define MX_SAI1                                 1

/* GPIO Configuration */

/* Pin PE5 */
#define MX_SAI1_SCK_A_GPIO_Speed                GPIO_SPEED_LOW
#define MX_SAI1_SCK_A_Pin                       PE5
#define MX_SAI1_SCK_A_GPIOx                     GPIOE
#define MX_SAI1_SCK_A_GPIO_PuPd                 GPIO_NOPULL
#define MX_SAI1_SCK_A_GPIO_Pin                  GPIO_PIN_5
#define MX_SAI1_SCK_A_GPIO_AF                   GPIO_AF6_SAI1
#define MX_SAI1_SCK_A_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PE4 */
#define MX_SAI1_FS_A_GPIO_Speed                 GPIO_SPEED_LOW
#define MX_SAI1_FS_A_Pin                        PE4
#define MX_SAI1_FS_A_GPIOx                      GPIOE
#define MX_SAI1_FS_A_GPIO_PuPd                  GPIO_NOPULL
#define MX_SAI1_FS_A_GPIO_Pin                   GPIO_PIN_4
#define MX_SAI1_FS_A_GPIO_AF                    GPIO_AF6_SAI1
#define MX_SAI1_FS_A_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PE6 */
#define MX_SAI1_SD_A_GPIO_Speed                 GPIO_SPEED_LOW
#define MX_SAI1_SD_A_Pin                        PE6
#define MX_SAI1_SD_A_GPIOx                      GPIOE
#define MX_SAI1_SD_A_GPIO_PuPd                  GPIO_NOPULL
#define MX_SAI1_SD_A_GPIO_Pin                   GPIO_PIN_6
#define MX_SAI1_SD_A_GPIO_AF                    GPIO_AF6_SAI1
#define MX_SAI1_SD_A_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PE3 */
#define MX_SAI1_SD_B_GPIO_Speed                 GPIO_SPEED_LOW
#define MX_SAI1_SD_B_Pin                        PE3
#define MX_SAI1_SD_B_GPIOx                      GPIOE
#define MX_SAI1_SD_B_GPIO_PuPd                  GPIO_NOPULL
#define MX_SAI1_SD_B_GPIO_Pin                   GPIO_PIN_3
#define MX_SAI1_SD_B_GPIO_AF                    GPIO_AF6_SAI1
#define MX_SAI1_SD_B_GPIO_Mode                  GPIO_MODE_AF_PP

/* DMA Configuration */

/* DMA SAI1_A */
#define MX_SAI1_A_DMA_MemBurst                  DMA_MBURST_SINGLE
#define MX_SAI1_A_DMA_Instance                  DMA2_Stream1
#define MX_SAI1_A_DMA_FIFOMode                  DMA_FIFOMODE_ENABLE
#define MX_SAI1_A_DMA_Priority                  DMA_PRIORITY_LOW
#define MX_SAI1_A_DMA_Channel                   DMA_CHANNEL_0
#define MX_SAI1_A_DMA_MemDataAlignment          DMA_MDATAALIGN_WORD
#define MX_SAI1_A_DMA_Mode                      DMA_CIRCULAR
#define MX_SAI1_A_DMA_Direction                 DMA_PERIPH_TO_MEMORY
#define MX_SAI1_A_DMA_PeriphBurst               DMA_PBURST_SINGLE
#define MX_SAI1_A_DMA_MemInc                    DMA_MINC_ENABLE
#define MX_SAI1_A_DMA_PeriphDataAlignment       DMA_PDATAALIGN_WORD
#define MX_SAI1_A_DMA_PeriphInc                 DMA_PINC_DISABLE
#define MX_SAI1_A_DMA_FIFOThreshold             DMA_FIFO_THRESHOLD_HALFFULL

/* DMA SAI1_B */
#define MX_SAI1_B_DMA_MemBurst                  DMA_MBURST_INC4
#define MX_SAI1_B_DMA_Instance                  DMA2_Stream4
#define MX_SAI1_B_DMA_FIFOMode                  DMA_FIFOMODE_ENABLE
#define MX_SAI1_B_DMA_Priority                  DMA_PRIORITY_LOW
#define MX_SAI1_B_DMA_Channel                   DMA_CHANNEL_1
#define MX_SAI1_B_DMA_MemDataAlignment          DMA_MDATAALIGN_WORD
#define MX_SAI1_B_DMA_Mode                      DMA_CIRCULAR
#define MX_SAI1_B_DMA_Direction                 DMA_PERIPH_TO_MEMORY
#define MX_SAI1_B_DMA_PeriphBurst               DMA_PBURST_INC4
#define MX_SAI1_B_DMA_MemInc                    DMA_MINC_ENABLE
#define MX_SAI1_B_DMA_PeriphDataAlignment       DMA_PDATAALIGN_WORD
#define MX_SAI1_B_DMA_PeriphInc                 DMA_PINC_DISABLE
#define MX_SAI1_B_DMA_FIFOThreshold             DMA_FIFO_THRESHOLD_HALFFULL

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/* Pin PA13 */
#define MX_SYS_JTMS-SWDIO_Pin                   PA13

/* Pin PA14 */
#define MX_SYS_JTCK-SWCLK_Pin                   PA14

/*-------------------------------- USART2     --------------------------------*/

#define MX_USART2                               1

#define MX_USART2_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PA0/WKUP */
#define MX_USART2_CTS_GPIO_Speed                GPIO_SPEED_HIGH
#define MX_USART2_CTS_Pin                       PA0/WKUP
#define MX_USART2_CTS_GPIOx                     GPIOA
#define MX_USART2_CTS_GPIO_PuPd                 GPIO_NOPULL
#define MX_USART2_CTS_GPIO_Pin                  GPIO_PIN_0
#define MX_USART2_CTS_GPIO_AF                   GPIO_AF7_USART2
#define MX_USART2_CTS_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PA2 */
#define MX_USART2_TX_GPIO_Speed                 GPIO_SPEED_HIGH
#define MX_USART2_TX_Pin                        PA2
#define MX_USART2_TX_GPIOx                      GPIOA
#define MX_USART2_TX_GPIO_PuPd                  GPIO_PULLUP
#define MX_USART2_TX_GPIO_Pin                   GPIO_PIN_2
#define MX_USART2_TX_GPIO_AF                    GPIO_AF7_USART2
#define MX_USART2_TX_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PA3 */
#define MX_USART2_RX_GPIO_Speed                 GPIO_SPEED_HIGH
#define MX_USART2_RX_Pin                        PA3
#define MX_USART2_RX_GPIOx                      GPIOA
#define MX_USART2_RX_GPIO_PuPd                  GPIO_PULLUP
#define MX_USART2_RX_GPIO_Pin                   GPIO_PIN_3
#define MX_USART2_RX_GPIO_AF                    GPIO_AF7_USART2
#define MX_USART2_RX_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PA1 */
#define MX_USART2_RTS_GPIO_Speed                GPIO_SPEED_HIGH
#define MX_USART2_RTS_Pin                       PA1
#define MX_USART2_RTS_GPIOx                     GPIOA
#define MX_USART2_RTS_GPIO_PuPd                 GPIO_NOPULL
#define MX_USART2_RTS_GPIO_Pin                  GPIO_PIN_1
#define MX_USART2_RTS_GPIO_AF                   GPIO_AF7_USART2
#define MX_USART2_RTS_GPIO_Mode                 GPIO_MODE_AF_PP

/*-------------------------------- USART3     --------------------------------*/

#define MX_USART3                               1

#define MX_USART3_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PB14 */
#define MX_USART3_RTS_GPIO_Speed                GPIO_SPEED_HIGH
#define MX_USART3_RTS_Pin                       PB14
#define MX_USART3_RTS_GPIOx                     GPIOB
#define MX_USART3_RTS_GPIO_PuPd                 GPIO_NOPULL
#define MX_USART3_RTS_GPIO_Pin                  GPIO_PIN_14
#define MX_USART3_RTS_GPIO_AF                   GPIO_AF7_USART3
#define MX_USART3_RTS_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PD8 */
#define MX_USART3_TX_GPIO_Speed                 GPIO_SPEED_HIGH
#define MX_USART3_TX_Pin                        PD8
#define MX_USART3_TX_GPIOx                      GPIOD
#define MX_USART3_TX_GPIO_PuPd                  GPIO_PULLUP
#define MX_USART3_TX_GPIO_Pin                   GPIO_PIN_8
#define MX_USART3_TX_GPIO_AF                    GPIO_AF7_USART3
#define MX_USART3_TX_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PB11 */
#define MX_USART3_RX_GPIO_Speed                 GPIO_SPEED_HIGH
#define MX_USART3_RX_Pin                        PB11
#define MX_USART3_RX_GPIOx                      GPIOB
#define MX_USART3_RX_GPIO_PuPd                  GPIO_PULLUP
#define MX_USART3_RX_GPIO_Pin                   GPIO_PIN_11
#define MX_USART3_RX_GPIO_AF                    GPIO_AF7_USART3
#define MX_USART3_RX_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PB13 */
#define MX_USART3_CTS_GPIO_Speed                GPIO_SPEED_HIGH
#define MX_USART3_CTS_Pin                       PB13
#define MX_USART3_CTS_GPIOx                     GPIOB
#define MX_USART3_CTS_GPIO_PuPd                 GPIO_NOPULL
#define MX_USART3_CTS_GPIO_Pin                  GPIO_PIN_13
#define MX_USART3_CTS_GPIO_AF                   GPIO_AF7_USART3
#define MX_USART3_CTS_GPIO_Mode                 GPIO_MODE_AF_PP

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

#endif  /* __MX_DEVICE_H */

